version: '3.8'

services:
  dcjoinsounds:
    build: .
    volumes:
      # Ses dosyaları için kalıcı depolama
      - app_downloads:/app/downloads
    env_file:
      - .env
    # Gerekli olmadıkça port yönlendirmesi yok
    network_mode: host

volumes:
  app_data:
  app_downloads:
